desc: deviceA
port: 4723
bp: 4724
ip: 127.0.0.1
desired_caps:
  #模拟器
#  deviceName: 127.0.0.1:62001
#  udid: 127.0.0.1:62001
#  platformVersion: 5.1.1
  deviceName: xxxx
  udid: e7a9d079
  platformVersion: 6.0.1
  platformName: Android
  automationName: uiautomator2
  systemPort: 8200
  appPackage: com.yozo.office
  noReset:  !!bool True
  appActivity: com.yozo.home.WelcomeActivity #真机需要从最开始的activity进入
#  appActivity: com.yozo.MainActivity
  newCommandTimeout: 120